### ISSUE TITLE
How can I Generate app.log file daily - datewise

### ISSUE THREAD

**Issue by rakhikhengar** [log4js-node/log4js-example#8]
I need help for generate app.log file on daily bases. 

I have added pattern in log4js.json file for "apps" that 
"app": {
        "type": "file",
        "filename": "./storage/logs/app.log",
        "maxLogSize": 10485760,
         "pattern": "-yyyy-MM-dd",        
        "numBackups": 3
      },
but  I'm getting error.  Please help me to generate app.log file dynamic date wise. like app-14-apr-2020.log

**Comment by rnd-debug** [comment]
You probably want to use the "dateFile" appender and not the "file" one. Check the docs: https://log4js-node.github.io/log4js-node/dateFile.html
